all: true
recursive: true
force-file-write: true
dir: "mocks/{{ .SrcPackagePath }}"
filename: "mock_{{ .InterfaceName }}.go"
pkgname: "{{ .SrcPackageName }}Mocks"
structname: "Mock{{ .InterfaceName }}"
template: testify
formatter: "goimports"
packages:
  github.com/thewizardplusplus/go-dos-protection:
