// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dosProtectorAdapterMiddlewaresMocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	dosProtectorUsecaseModels "github.com/thewizardplusplus/go-dos-protector/usecases/models"
	pow "github.com/thewizardplusplus/go-pow"
)

// NewMockDoSProtectorUsecase creates a new instance of MockDoSProtectorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoSProtectorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoSProtectorUsecase {
	mock := &MockDoSProtectorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoSProtectorUsecase is an autogenerated mock type for the DoSProtectorUsecase type
type MockDoSProtectorUsecase struct {
	mock.Mock
}

type MockDoSProtectorUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoSProtectorUsecase) EXPECT() *MockDoSProtectorUsecase_Expecter {
	return &MockDoSProtectorUsecase_Expecter{mock: &_m.Mock}
}

// GenerateSignedChallenge provides a mock function for the type MockDoSProtectorUsecase
func (_mock *MockDoSProtectorUsecase) GenerateSignedChallenge(ctx context.Context) (dosProtectorUsecaseModels.SignedChallenge, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSignedChallenge")
	}

	var r0 dosProtectorUsecaseModels.SignedChallenge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (dosProtectorUsecaseModels.SignedChallenge, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) dosProtectorUsecaseModels.SignedChallenge); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(dosProtectorUsecaseModels.SignedChallenge)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDoSProtectorUsecase_GenerateSignedChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSignedChallenge'
type MockDoSProtectorUsecase_GenerateSignedChallenge_Call struct {
	*mock.Call
}

// GenerateSignedChallenge is a helper method to define mock.On call
//   - ctx
func (_e *MockDoSProtectorUsecase_Expecter) GenerateSignedChallenge(ctx interface{}) *MockDoSProtectorUsecase_GenerateSignedChallenge_Call {
	return &MockDoSProtectorUsecase_GenerateSignedChallenge_Call{Call: _e.mock.On("GenerateSignedChallenge", ctx)}
}

func (_c *MockDoSProtectorUsecase_GenerateSignedChallenge_Call) Run(run func(ctx context.Context)) *MockDoSProtectorUsecase_GenerateSignedChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDoSProtectorUsecase_GenerateSignedChallenge_Call) Return(signedChallenge dosProtectorUsecaseModels.SignedChallenge, err error) *MockDoSProtectorUsecase_GenerateSignedChallenge_Call {
	_c.Call.Return(signedChallenge, err)
	return _c
}

func (_c *MockDoSProtectorUsecase_GenerateSignedChallenge_Call) RunAndReturn(run func(ctx context.Context) (dosProtectorUsecaseModels.SignedChallenge, error)) *MockDoSProtectorUsecase_GenerateSignedChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySolutionAndChallengeSignature provides a mock function for the type MockDoSProtectorUsecase
func (_mock *MockDoSProtectorUsecase) VerifySolutionAndChallengeSignature(ctx context.Context, params dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams) (pow.Solution, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for VerifySolutionAndChallengeSignature")
	}

	var r0 pow.Solution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams) (pow.Solution, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams) pow.Solution); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(pow.Solution)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySolutionAndChallengeSignature'
type MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call struct {
	*mock.Call
}

// VerifySolutionAndChallengeSignature is a helper method to define mock.On call
//   - ctx
//   - params
func (_e *MockDoSProtectorUsecase_Expecter) VerifySolutionAndChallengeSignature(ctx interface{}, params interface{}) *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call {
	return &MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call{Call: _e.mock.On("VerifySolutionAndChallengeSignature", ctx, params)}
}

func (_c *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call) Run(run func(ctx context.Context, params dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams)) *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams))
	})
	return _c
}

func (_c *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call) Return(solution pow.Solution, err error) *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call {
	_c.Call.Return(solution, err)
	return _c
}

func (_c *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call) RunAndReturn(run func(ctx context.Context, params dosProtectorUsecaseModels.VerifySolutionAndChallengeSignatureParams) (pow.Solution, error)) *MockDoSProtectorUsecase_VerifySolutionAndChallengeSignature_Call {
	_c.Call.Return(run)
	return _c
}
