// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dosProtectorAdapterMiddlewaresMocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoadLevelRegister creates a new instance of MockLoadLevelRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadLevelRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadLevelRegister {
	mock := &MockLoadLevelRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoadLevelRegister is an autogenerated mock type for the LoadLevelRegister type
type MockLoadLevelRegister struct {
	mock.Mock
}

type MockLoadLevelRegister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadLevelRegister) EXPECT() *MockLoadLevelRegister_Expecter {
	return &MockLoadLevelRegister_Expecter{mock: &_m.Mock}
}

// DecreaseLoadLevel provides a mock function for the type MockLoadLevelRegister
func (_mock *MockLoadLevelRegister) DecreaseLoadLevel(delta int) {
	_mock.Called(delta)
	return
}

// MockLoadLevelRegister_DecreaseLoadLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseLoadLevel'
type MockLoadLevelRegister_DecreaseLoadLevel_Call struct {
	*mock.Call
}

// DecreaseLoadLevel is a helper method to define mock.On call
//   - delta
func (_e *MockLoadLevelRegister_Expecter) DecreaseLoadLevel(delta interface{}) *MockLoadLevelRegister_DecreaseLoadLevel_Call {
	return &MockLoadLevelRegister_DecreaseLoadLevel_Call{Call: _e.mock.On("DecreaseLoadLevel", delta)}
}

func (_c *MockLoadLevelRegister_DecreaseLoadLevel_Call) Run(run func(delta int)) *MockLoadLevelRegister_DecreaseLoadLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockLoadLevelRegister_DecreaseLoadLevel_Call) Return() *MockLoadLevelRegister_DecreaseLoadLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoadLevelRegister_DecreaseLoadLevel_Call) RunAndReturn(run func(delta int)) *MockLoadLevelRegister_DecreaseLoadLevel_Call {
	_c.Run(run)
	return _c
}

// IncreaseLoadLevel provides a mock function for the type MockLoadLevelRegister
func (_mock *MockLoadLevelRegister) IncreaseLoadLevel(delta int) {
	_mock.Called(delta)
	return
}

// MockLoadLevelRegister_IncreaseLoadLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseLoadLevel'
type MockLoadLevelRegister_IncreaseLoadLevel_Call struct {
	*mock.Call
}

// IncreaseLoadLevel is a helper method to define mock.On call
//   - delta
func (_e *MockLoadLevelRegister_Expecter) IncreaseLoadLevel(delta interface{}) *MockLoadLevelRegister_IncreaseLoadLevel_Call {
	return &MockLoadLevelRegister_IncreaseLoadLevel_Call{Call: _e.mock.On("IncreaseLoadLevel", delta)}
}

func (_c *MockLoadLevelRegister_IncreaseLoadLevel_Call) Run(run func(delta int)) *MockLoadLevelRegister_IncreaseLoadLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockLoadLevelRegister_IncreaseLoadLevel_Call) Return() *MockLoadLevelRegister_IncreaseLoadLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoadLevelRegister_IncreaseLoadLevel_Call) RunAndReturn(run func(delta int)) *MockLoadLevelRegister_IncreaseLoadLevel_Call {
	_c.Run(run)
	return _c
}
