// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dosProtectorUsecasesMocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	powValueTypes "github.com/thewizardplusplus/go-pow/value-types"
)

// NewMockLeadingZeroBitCountProvider creates a new instance of MockLeadingZeroBitCountProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeadingZeroBitCountProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeadingZeroBitCountProvider {
	mock := &MockLeadingZeroBitCountProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLeadingZeroBitCountProvider is an autogenerated mock type for the LeadingZeroBitCountProvider type
type MockLeadingZeroBitCountProvider struct {
	mock.Mock
}

type MockLeadingZeroBitCountProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeadingZeroBitCountProvider) EXPECT() *MockLeadingZeroBitCountProvider_Expecter {
	return &MockLeadingZeroBitCountProvider_Expecter{mock: &_m.Mock}
}

// ProvideLeadingZeroBitCount provides a mock function for the type MockLeadingZeroBitCountProvider
func (_mock *MockLeadingZeroBitCountProvider) ProvideLeadingZeroBitCount(ctx context.Context) (powValueTypes.LeadingZeroBitCount, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProvideLeadingZeroBitCount")
	}

	var r0 powValueTypes.LeadingZeroBitCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (powValueTypes.LeadingZeroBitCount, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) powValueTypes.LeadingZeroBitCount); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(powValueTypes.LeadingZeroBitCount)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvideLeadingZeroBitCount'
type MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call struct {
	*mock.Call
}

// ProvideLeadingZeroBitCount is a helper method to define mock.On call
//   - ctx
func (_e *MockLeadingZeroBitCountProvider_Expecter) ProvideLeadingZeroBitCount(ctx interface{}) *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call {
	return &MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call{Call: _e.mock.On("ProvideLeadingZeroBitCount", ctx)}
}

func (_c *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call) Run(run func(ctx context.Context)) *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call) Return(leadingZeroBitCount powValueTypes.LeadingZeroBitCount, err error) *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call {
	_c.Call.Return(leadingZeroBitCount, err)
	return _c
}

func (_c *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call) RunAndReturn(run func(ctx context.Context) (powValueTypes.LeadingZeroBitCount, error)) *MockLeadingZeroBitCountProvider_ProvideLeadingZeroBitCount_Call {
	_c.Call.Return(run)
	return _c
}
